
inherit:
  - wilds_transfer.yaml 
  - datasets_fmow_noaugment.yaml

num_classes: 62
epochs: &epochs 50

model:
  classname: models.imnet_models.WildsVisionModel
  args:
    name: 'densenet121'
    pretrained: True
    num_classes: 62 

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

train_dataset:
    classname: datasets.fmow.Fmow
    args:
        split: 'train'
        regions: [0,1,2,3,4,5] 
        root: 'wilds/data'
    transforms:
        - classname: torchvision.transforms.ToTensor
        - classname: torchvision.transforms.Normalize
          args:
              mean: [0.485, 0.456, 0.406]
              std: [0.2289, 0.224, 0.225]

