
inherit:
  - wilds_transfer.yaml 
  - datasets_fmow_noaugment.yaml

num_classes: 62
epochs: &epochs 50

model:
  classname: models.imnet_models.WildsVisionModel
  args:
    name: 'densenet121'
    pretrained: True
    checkpoint_path: '/sailhome/ananya/scratch/cifar_experiments/wilds/logs/fmow_seed:0_epoch:best_model.pth'
    num_classes: 62 

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

