
inherit:
  - resnet50_transfer.yaml 
  - datasets_e30_swav_noaugment.yaml

num_classes: 30

model:
  classname: models.imnet_resnet.ResNet50
  args:
    pretrained: True
    pretrain_style: 'swav'
    checkpoint_path: '/u/scr/ananya/simclr_weights/swav_800ep_pretrain.pth.tar'

