
inherit:
  - resnet50_transfer.yaml 
  - datasets_l17_swav_augment.yaml

num_classes: 17
epochs: &epochs 100

model:
  classname: models.imnet_resnet.ResNet50
  args:
    pretrained: True
    pretrain_style: 'supervised'

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

