
log_interval: 5000
use_cuda: True
save_freq: 1001
batch_size: 64
num_workers: 2
save_all_checkpoints: False

finetune: True
use_net_val_mode: True

optimizer:
  classname: torch.optim.SGD
  args:
    lr: 0.03
    momentum: 0.9

model:
  classname: models.imnet_resnet.ResNet50
  args:
    pretrained: True

criterion:
  classname: torch.nn.CrossEntropyLoss
  args:
    reduction: mean

