
inherit:
  - resnet50_transfer.yaml 
  - datasets_camelyon17_weakaugs.yaml

num_classes: 2
epochs: &epochs 3
batch_size: 32
batch_splits: 2
save_no_checkpoints: True
save_wilds_model_preds: True

model:
  classname: models.imnet_resnet.ResNet50
  args: {}

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs
