
root_prefix: '/u/scr/nlp/domainnet'

# The train and test transforms are taken from Sentry.
# Except the normalization and the bicubic resampling, taken from CLIP.
train_dataset:
    name: 'sketch_train'
    classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
    args:
        domain: 'sketch'
        split: 'train'
        root: ''
        version: 'sentry'
        verbose: False
    transforms:
        - classname: unlabeled_extrapolation.datasets.transforms.Resize
          args:
              size: [256, 256]
              interpolation: 'bicubic'
        - classname: torchvision.transforms.RandomCrop
          args:
              size: 224
        - classname: torchvision.transforms.RandomHorizontalFlip
        - classname: torchvision.transforms.ToTensor

default_test_transforms:
    - classname: unlabeled_extrapolation.datasets.transforms.Resize
      args:
          size: [224, 224]
          interpolation: 'bicubic'
    - classname: torchvision.transforms.ToTensor

test_datasets:
    - name: 'sketch_val'
      classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
      args:
          domain: 'sketch'
          split: 'test'
          root: ''
          version: 'sentry'
          verbose: False
    - name: 'real_val'
      classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
      args:
          domain: 'real'
          split: 'test'
          root: ''
          version: 'sentry'
          verbose: False
    - name: 'painting_val'
      classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
      args:
          domain: 'painting'
          split: 'test'
          root: ''
          version: 'sentry'
          verbose: False
    - name: 'clipart_val'
      classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
      args:
          domain: 'clipart'
          split: 'test'
          root: ''
          version: 'sentry'
          verbose: False

early_stop_dataset_names:
    - 'sketch_val'
    - 'real_val'
