
root_prefix: '/u/scr/nlp/wilds/data/'

train_dataset:
    name: 'train'
    classname: datasets.wilds.WILDS
    args:
        dataset_name: 'camelyon17'
        split: 'train'
        root: ''
    transforms:
        - classname: torchvision.transforms.Resize
          args:
              size: [224, 224]
        - classname: torchvision.transforms.RandomHorizontalFlip  
        - classname: torchvision.transforms.ToTensor

default_test_transforms:
    - classname: torchvision.transforms.Resize
      args:
          size: [224, 224]
    - classname: torchvision.transforms.ToTensor

test_datasets:
    - name: 'id_val'
      classname: datasets.wilds.WILDS
      args:
          dataset_name: 'camelyon17'
          split: 'id_val'
          root: ''
    - name: 'ood_val'
      classname: datasets.wilds.WILDS
      args:
          dataset_name: 'camelyon17'
          split: 'val'
          root: ''
    - name: 'ood_test'
      classname: datasets.wilds.WILDS
      args:
          dataset_name: 'camelyon17'
          split: 'test'
          root: ''

early_stop_dataset_names:
    - 'id_val'
    - 'ood_val'
