
root_prefix: '/u/scr/nlp/wilds/data/'

# Add augmentations, and change normalization a bit.
# The difference is swav augmentation has a 0.228 instead of 0.229 (lol)
# Probably doesn't make a difference.
train_dataset:
    name: 'fmow-train'
    classname: datasets.fmow.Fmow
    args:
        split: 'train'
        regions: [3] 
        root: ''
    transforms:
        - classname: torchvision.transforms.ToTensor
        - classname: torchvision.transforms.Normalize
          args:
              mean: [0.485, 0.456, 0.406]
              std: [0.2289, 0.224, 0.225]

# Change transform (e.g. centercrop), and change normalization a bit.
default_test_transforms:
    - classname: torchvision.transforms.ToTensor
    - classname: torchvision.transforms.Normalize
      args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

test_datasets:
    - name: 'europe_val'
      classname: datasets.fmow.Fmow
      args:
          split: 'val'
          regions: [1]
          root: ''
    - name: 'africa_val'
      classname: datasets.fmow.Fmow
      args:
          split: 'val'
          regions: [2]
          root: ''
    - name: 'americas_val'
      classname: datasets.fmow.Fmow
      args:
          split: 'val'
          regions: [3]
          root: ''

early_stop_dataset_names:
    - 'americas_val'
    - 'africa_val'
