
root_prefix: '/scr/biggest/'

# The train and test transforms are taken from Sentry.
# Except the normalization and the bicubic resampling, taken from CLIP.
train_dataset:
    name: 'sketch_train'
    classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
    args:
        domain: 'sketch'
        split: 'train'
        root: 'domainnet/'
        version: 'sentry'
        verbose: False
    transforms:
        - classname: unlabeled_extrapolation.datasets.transforms.Resize
          args:
              size: [256, 256]
              interpolation: 'bicubic'
        - classname: torchvision.transforms.RandomCrop
          args:
              size: 224
        - classname: torchvision.transforms.RandomHorizontalFlip
        - classname: torchvision.transforms.ToTensor
        - classname: torchvision.transforms.Normalize
          args:
              mean: [0.48145466, 0.4578275, 0.40821073]
              std: [0.26862954, 0.26130258, 0.27577711]

default_test_transforms:
    - classname: unlabeled_extrapolation.datasets.transforms.Resize
      args:
          size: [256, 256]
          interpolation: 'bicubic'
    - classname: torchvision.transforms.ToTensor
    - classname: torchvision.transforms.Normalize
      args:
          mean: [0.48145466, 0.4578275, 0.40821073]
          std: [0.26862954, 0.26130258, 0.27577711]

test_datasets:
    - name: 'sketch_val'
      classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
      args:
          domain: 'sketch'
          split: 'test'
          root: 'domainnet/'
          version: 'sentry'
          verbose: False
    - name: 'real_val'
      classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
      args:
          domain: 'real'
          split: 'test'
          root: 'domainnet/'
          version: 'sentry'
          verbose: False
    - name: 'painting_val'
      classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
      args:
          domain: 'painting'
          split: 'test'
          root: 'domainnet/'
          version: 'sentry'
          verbose: False
    - name: 'clipart_val'
      classname: unlabeled_extrapolation.datasets.domainnet.DomainNet
      args:
          domain: 'clipart'
          split: 'test'
          root: 'domainnet/'
          version: 'sentry'
          verbose: False

early_stop_dataset_names:
    - 'sketch-test'
    - 'real-test'
