
inherit:
  - resnet50_transfer.yaml 
  - datasets_domainnet.yaml

num_classes: 40
epochs: &epochs 500  # Very small dataset so run for much longer.

model:
  classname: models.clip_model.ClipModel
  args:
    model_name: 'RN50'

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

