
inherit:
  - resnet50_transfer.yaml 
  - datasets_domainnet.yaml

num_classes: 40
epochs: &epochs 50  # Very small dataset so run for longer.
batch_size: 32
batch_splits: 2
save_no_checkpoints: True

model:
  classname: models.clip_model.ClipModel
  args: {}

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

