
inherit:
  - resnet50_transfer.yaml 
  - datasets_entity30.yaml

num_classes: 30
epochs: &epochs 50

model:
  classname: models.imnet_resnet.ResNet50
  args:
    pretrained: True
    pretrain_style: 'mocov2'
    checkpoint_path: ''

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

