
inherit:
  - resnet50_transfer.yaml 

num_classes: 62
epochs: &epochs 5
batch_size: 32
batch_splits: 4
save_no_checkpoints: True
save_wilds_model_preds: True

model:
  classname: models.imnet_resnet.ResNet50
  args: {}

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

root_prefix: '/u/scr/nlp/wilds/data'

# Add augmentations, and change normalization a bit.
# The difference is swav augmentation has a 0.228 instead of 0.229 (lol)
# Probably doesn't make a difference.
train_dataset:
    name: 'train'
    classname: datasets.fmow.Fmow
    args:
        split: 'train'
        regions: ['all'] 
        root: ''
    transforms:
        - classname: unlabeled_extrapolation.datasets.transforms.Resize
          args:
              size: [336, 336]
              interpolation: 'bicubic'
        - classname: torchvision.transforms.RandomHorizontalFlip
        - classname: torchvision.transforms.ToTensor

# Change transform (e.g. centercrop), and change normalization a bit.
default_test_transforms:
    - classname: unlabeled_extrapolation.datasets.transforms.Resize
      args:
          size: [336, 336]
          interpolation: 'bicubic'
    - classname: torchvision.transforms.ToTensor

test_datasets:
    - name: 'id_val'
      classname: datasets.fmow.Fmow
      args:
          split: 'id_val'
          regions: ['all']
          root: ''
    - name: 'id_test'
      classname: datasets.fmow.Fmow
      args:
          split: 'id_test'
          regions: ['all']
          root: ''
    - name: 'ood_val'
      classname: datasets.fmow.Fmow
      args:
          split: 'val'
          regions: ['all']
          root: ''
    - name: 'ood_test'
      classname: datasets.fmow.Fmow
      args:
          split: 'test'
          regions: ['all']
          root: ''
    - name: 'africa_test'
      classname: datasets.fmow.Fmow
      args:
          split: 'test'
          regions: [2]
          root: ''

early_stop_dataset_names:
    - 'id_val'
    - 'ood_val'
