
inherit:
  - resnet50_transfer.yaml 
  - datasets_imagenet.yaml

num_classes: 30
epochs: &epochs 5

model:
  classname: models.clip_model.ClipModel
  args:
    model_name: 'RN50'

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs
