
inherit:
  - resnet50_transfer.yaml 
  - datasets_living17_nonorm.yaml

num_classes: 17
epochs: &epochs 20
save_no_checkpoints: True

model:
  classname: models.imnet_resnet.ResNet50
  args: {}

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

