
inherit:
  - resnet50_transfer.yaml 
  - datasets_waterbirds_augs.yaml

num_classes: 2
epochs: &epochs 100
batch_size: 64
save_no_checkpoints: True

model:
  classname: models.imnet_resnet.ResNet50
  args: {}

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs
