
inherit:
  - landcover_transfer.yaml 
  - datasets_landcover_from_africa.yaml

num_classes: 6
epochs: &epochs 25

model:
  classname: models.innout_models.CNN1D
  args:
    in_channels: 8
    output_size: 6
    checkpoint_path: '/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/pretrained_checkpoints/landcover/best-checkpoint.pt'

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

