
batch_size: 64
num_workers: 2
use_cuda: False
save_path: '/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/logs/extract_features/landcover_to_africa_cnn'

config_paths:
  - '/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/logs/landcover_to_africa_ft_sweep/0.01_0/config.json'

checkpoint_paths:
  - '/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/logs/landcover_to_africa_ft_sweep/0.01_0/checkpoints/ckp_0'

model_names:
  - 'cnn1d'

loader_names:
  - 'nonafrica-train'
  - 'nonafrica-val'
  - 'africa-train'
  - 'africa-val'

split_names:
  - 'nonafrica-train'
  - 'nonafrica-val'
  - 'africa-train'
  - 'africa-val'

split_arg_names:
  - 'split'
  - 'split'
  - 'split'
  - 'split'

# Relative to the config file in the first config path in config_paths.
loader_indices:
  - 0
  - 0
  - 0
  - 0

