log_interval: 5000
use_cuda: True
save_freq: 25
epochs: &epochs 100
batch_size: 128
num_workers: 8
save_all_checkpoints: False

finetune: True
num_classes: 10
linear_probe: True
use_net_val_mode: True

# probe_net:
#   classname: models.mlp.MLP
#   args:
#     dims: [2048, 64, 64]
#     output_dim: 10

optimizer:
  classname: torch.optim.SGD
  args:
    lr: 0.1
    momentum: 0.9

# scheduler:
#   classname: torch.optim.lr_scheduler.StepLR
#   args:
#     step_size: *epochs

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

model:
  classname: models.imnet_resnet.ResNet50
  args:
    pretrained: True

train_dataset:
    classname: torchvision.datasets.CIFAR10
    args:
        train: True
        download: False
        root: '/u/scr/ananya/cifar10_dataset'
    transforms:
        - classname: torchvision.transforms.Resize
          args:
              size: 224
        - classname: torchvision.transforms.ToTensor
        - classname: torchvision.transforms.Normalize
          args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]

default_test_transforms:
    - classname: torchvision.transforms.Resize
      args:
          size: 224
    - classname: torchvision.transforms.ToTensor
    - classname: torchvision.transforms.Normalize
      args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

test_datasets:
    - name: 'cifar10-test'
      classname: torchvision.datasets.CIFAR10
      args:
          train: False
          download: False
          root: '/u/scr/ananya/cifar10_dataset'
    - name: 'stl-test'
      classname: datasets.stl_cifar_style.STL10
      args:
          root: '/u/scr/ananya/stl10_dataset'
          split: 'test'
    - name: 'cinic-val'
      classname: datasets.cinic.CINICImNet
      max_test_examples: 10000
      args:
          root: '/u/scr/ananya/cinic-10-imagenet'
          mode: 'valid'

criterion:
  classname: torch.nn.CrossEntropyLoss
  args:
    reduction: mean

