
inherit:
    - datasets_breeds_living.yaml
    - resnet50_transfer.yaml

epochs: &epochs 25

finetune: True
num_classes: 17
linear_probe: False
use_net_val_mode: False

scheduler:
  classname: torch.optim.lr_scheduler.StepLR
  args:
    step_size: *epochs

