
inherit:
    - datasets_breeds_living.yaml
    - resnet50_transfer.yaml

epochs: &epochs 25

num_classes: 17
finetune: True
linear_probe: False
use_net_val_mode: False

scheduler:
  classname: torch.optim.lr_scheduler.StepLR
  args:
    step_size: *epochs

model:
  classname: models.imnet_resnet.ResNet50
  args:
    pretrained: True
    pretrain_style: 'mocov2'
    checkpoint_path: '/u/scr/ananya/simclr_weights/moco_v2_800ep_pretrain.pth.tar'

