
train_dataset:
    classname: torchvision.datasets.CIFAR10
    args:
        train: True
        download: False
        root: '/u/scr/ananya/cifar10_dataset'
    transforms:
        - classname: torchvision.transforms.Resize
          args:
              size: 224
        - classname: torchvision.transforms.ToTensor
        - classname: torchvision.transforms.Normalize
          args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]

default_test_transforms:
    - classname: torchvision.transforms.Resize
      args:
          size: [224, 224]
    - classname: torchvision.transforms.ToTensor
    - classname: torchvision.transforms.Normalize
      args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

test_datasets:
    - name: 'cifar10-test'
      max_test_examples: 1000
      classname: torchvision.datasets.CIFAR10
      args:
          train: False
          download: False
          root: '/u/scr/ananya/cifar10_dataset'
    - name: 'stl-test'
      max_test_examples: 1000
      classname: datasets.stl_cifar_style.STL10
      args:
          root: '/u/scr/ananya/stl10_dataset'
          split: 'test'
    - name: 'cinic-val'
      classname: datasets.cinic.CINICImNet
      max_test_examples: 1000
      args:
          root: '/u/scr/ananya/cinic-10-imagenet'
          mode: 'valid'
    - name: 'stl-32x32'
      classname: datasets.stl_cifar_style.STL10
      max_test_examples: 1000
      args:
          root: '/u/scr/ananya/stl10_dataset'
          split: 'test'
      transforms:
        - classname: torchvision.transforms.Resize
          args:
              size: 32
        - classname: torchvision.transforms.Resize
          args:
              size: 224
        - classname: torchvision.transforms.ToTensor
        - classname: torchvision.transforms.Normalize
          args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
    - name: 'imnet-n-cifar'
      classname: datasets.imnet_intersect_c10.ImNetnC10
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/balanced_imnet_intersect_c10_val/'
    - name: 'fog-cifar-2'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'fog'
          severity: 2
    - name: 'fog-cifar-4'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'fog'
          severity: 4
    - name: 'zoom-blur-cifar-2'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'zoom_blur'
          severity: 2
    - name: 'zoom-blur-cifar-4'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'zoom_blur'
          severity: 4
    - name: 'gaussian-cifar-2'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'gaussian_noise'
          severity: 2
    - name: 'gaussian-cifar-4'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'gaussian_noise'
          severity: 4
    - name: 'pixelate-cifar-2'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'pixelate'
          severity: 2
    - name: 'pixelate-cifar-4'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'pixelate'
          severity: 4
    - name: 'shotnoise-cifar-2'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'shot_noise'
          severity: 2
    - name: 'shotnoise-cifar-4'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'shot_noise'
          severity: 4
    - name: 'glassblur-cifar-2'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'glass_blur'
          severity: 2
    - name: 'glassblur-cifar-4'
      classname: datasets.cifar10c.CIFAR10C
      max_test_examples: 1000
      args:
          root: '/juice/scr/ananya/CIFAR-10-C/'
          corruption: 'glass_blur'
          severity: 4

