
train_dataset:
    classname: datasets.breeds.Breeds
    args:
        source: True
        split: 'train'
        breeds_name: 'entity30'
        root: '/u/scr/nlp/imagenet/'
    transforms:
        - classname: torchvision.transforms.Resize
          args:
              size: [224, 224]
        - classname: torchvision.transforms.ToTensor
        - classname: torchvision.transforms.Normalize
          args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]

default_test_transforms:
    - classname: torchvision.transforms.Resize
      args:
          size: [224, 224]
    - classname: torchvision.transforms.ToTensor
    - classname: torchvision.transforms.Normalize
      args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

test_datasets:
    - name: 'source_val_entity'
      classname: datasets.breeds.Breeds
      args:
          source: True
          split: 'val'
          breeds_name: 'entity30'
          root: '/u/scr/nlp/imagenet/'
    - name: 'target_val_entity'
      classname: datasets.breeds.Breeds
      args:
          source: False
          split: 'val'
          breeds_name: 'entity30'
          root: '/u/scr/nlp/imagenet/'
