
inherit: datasets_cifar_test_all.yaml

log_interval: 5000
use_cuda: True
save_freq: 101
epochs: &epochs 100
batch_size: 128
num_workers: 8
save_all_checkpoints: False

finetune: True
num_classes: 10
linear_probe: True
use_net_val_mode: True

optimizer:
  classname: torch.optim.SGD
  args:
    lr: 0.01
    momentum: 0.9

scheduler:
  classname: torch.optim.lr_scheduler.StepLR
  args:
    step_size: *epochs

model:
  classname: models.imnet_resnet.ResNet50
  args:
    pretrained: True

criterion:
  classname: torch.nn.CrossEntropyLoss
  args:
    reduction: mean

