log_interval: 10
use_cuda: True
save_freq: 25
epochs: &epochs 200
batch_size: 128
num_workers: 8
save_all_checkpoints: False

optimizer:
  classname: torch.optim.SGD
  args:
    lr: &lr 0.01
    momentum: 0.9

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    lr: *lr
    T_max: *epochs

model:
  classname: models.resnet.resnet18
  args:
    pretrained: True

train_dataset:
    classname: torchvision.datasets.CIFAR10
    args:
        train: True
        download: False
        root: '/u/scr/ananya/cifar10_dataset'
    transforms:
        - classname: torchvision.transforms.RandomCrop
          args:
              size: 32
              padding: 4
        - classname: torchvision.transforms.RandomHorizontalFlip
        - classname: torchvision.transforms.ToTensor

test_dataset:
    classname: torchvision.datasets.CIFAR10
    args:
        train: False
        download: False
        root: '/u/scr/ananya/cifar10_dataset'
    transforms:
        - classname: torchvision.transforms.ToTensor

criterion:
  classname: torch.nn.CrossEntropyLoss
  args:
    reduction: mean

