target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itplabrr1cl1
  vc: resrchvc

environment:
  image: pytorch/pytorch:latest
  registry: docker.io # any public registry can be specified here
  setup:
    - apt-get update
    - apt-get install git
    - pip install ./CLIP
    - pip install -e .

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: .

# data:
#   data upload is not required for this example

jobs:
  - name: test_job
    sku: G1-V100-P100
    command:
    - python unlabeled_extrapolation/baseline_train.py --config=configs/adaptation/waterbirds.yaml --root_prefix=. --log_dir=$$AMLT_OUTPUT_DIR --batch_size=16 --train_dataset.args.download=True --no_wandb
